name: Go

# cSpell:ignore covermode,benchtime

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.19.x, 1.20.x]
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go ${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Fetch Repository
        uses: actions/checkout@v2
      - name: Make Ready
        run: |
          go version
          go env
          go get -t -v ./...
          git rev-parse --short HEAD
      - name: Run Vet
        run: go vet ./...
      - name: Run Test
        run: go test -v -cover -covermode=atomic ./...
  # disabled bench to conserve Github Actions minutes
  # bench:
  #   name: Benchmark
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Install Go
  #       uses: actions/setup-go@v2
  #       with:
  #         go-version: 1.20.x
  #     - name: Fetch Repository
  #       uses: actions/checkout@v2
  #     - name: Run Benchmark
  #       run: go test ./... -bench=. -benchmem
